pluginManagement {
    repositories {
        maven { url = 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public/' }
        maven { url = 'https://maven.aliyun.com/repository/public' }
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public/'
        }
        maven { url = 'https://maven.aliyun.com/repository/public' }
        maven { url = 'https://maven.parchmentmc.org' }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.7.0'
}
